# https://wttech.blog/blog/2021/how-to-push-docker-image-to-digitalocean-container-registry-using-github-actions/
# This workflow sends the docker image to the DigitalOcean Container Registry with the "latest" tag. Saves a lot of space doing it this way.
name: Build and publish automatically on tag pushes
on:
  push:
    tags:
      - '*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
      - name: Build image 
        run: docker build --no-cache --progress=plain --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} --build-arg DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} --build-arg DISCORD_APPLICATION_ID=${{ secrets.DISCORD_APPLICATION_ID }} -t discordkarmabot . 
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
      - name: Tag image 
        run:
          docker tag discordkarmabot \registry.digitalocean.com/discordkarmabot/discordkarmabot:latest
      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/discordkarmabot/discordkarmabot:latest